;; //////////////////////////////////////////////////////////////////
;; WXP.module
;; 
;; (c) 2012 Traduções de Jogos,ltd.
;; 

[global]

UIName = $1101900
Description = Translation Games verify.
DllName = WXPMod
ModFolder = WXP
ModVersion = 1.0
TextureFE = Art/UI/Textures/Title_winter_assault.tga
TextureIcon =

;; //////////////////////////////////////////////////////////////////
;; List of folders to map for this MOD 
;; order is important - the first Archives registered will be scanned for files first
DataFolder.1 = %LOCALE%\Data
DataFolder.2 = Data
DataFolder.3 = Data_Shared_Textures\%TEXTURE-LEVEL%
DataFolder.4 = Data_Sound\%SOUND-LEVEL%
DataFolder.5 = Data_Music
DataFolder.6 = Data_Whm\%MODEL-LEVEL%

;; //////////////////////////////////////////////////////////////////
;; List of archives to load for this MOD 
;; order is important - the first Archives registered will be scanned for files first
ArchiveFile.1 = %LOCALE%\WXPDataLoc
ArchiveFile.2 = %LOCALE%\WXPDataKeys
ArchiveFile.3 = WXPData
ArchiveFile.4 = WXPData-SharedTextures-%TEXTURE-LEVEL%
ArchiveFile.5 = %LOCALE%\WXPData-Sound-Speech
ArchiveFile.6 = WXPData-Sound-%SOUND-LEVEL%
ArchiveFile.7 = WXPData-Music
ArchiveFile.8 = WXPData-Whm-%MODEL-LEVEL%

;; //////////////////////////////////////////////////////////////////
;; List of MODs that this MOD requires to work
RequiredMod.1 = W40k
